# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCtxe6JGxiFkz6ZTQ3Wt3v_nQZazZEdp
"""

from flask import Flask, request, jsonify
import pandas as pd
import xgboost as xgb
import pickle

app = Flask(__name__)

# โหลดโมเดล XGBoost จากไฟล์ model.pkl
model = pickle.load(open("model.pkl", "rb"))

# คอลัมน์ฟีเจอร์ที่โมเดลต้องการ
columns = [
    "Age", "Loan_amount", "Occupation", "Gender", "Experience", "Income",
    "Customer_province", "Current_address_province", "Work_address_province",
    "Product", "Vehicle_brand", "Release_year", "Channel", "Owner_Case", "Region_Flag",
    "Phone_Number", "Name_Code",
    "num_guarantor", "phone_count", "guarantee_others", "guarantee_network_size"
]

@app.route("/")
def home():
    return "✅ Fraud Detection API is running!"

@app.route("/predict", methods=["POST"])
def predict():
    try:
        data = request.get_json()
        df = pd.DataFrame([data], columns=columns)
        y_pred = model.predict(df)[0]
        y_prob = model.predict_proba(df)[0].tolist()
        return jsonify({
            "prediction": int(y_pred),
            "probability": y_prob
        })
    except Exception as e:
        return jsonify({"error": str(e)})

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)